# Generated by Django 3.2.7 on 2021-10-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('idAnuncio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=13)),
                ('departamento', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('vigencia', models.BooleanField()),
                ('permitido', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('idPaquete', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('cantidadAnuncios', models.SmallIntegerField(default=1)),
                ('duracionDias', models.SmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vigencia', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('vigencia', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('idTarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTarjeta', models.CharField(max_length=50)),
                ('numeroTarjeta', models.CharField(max_length=19)),
                ('fechaExpiracion', models.DateField()),
                ('cvc', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=20)),
                ('cuenta', models.CharField(max_length=80, unique=True)),
                ('telefono', models.CharField(max_length=13)),
                ('descripcionUsuario', models.CharField(max_length=200, null=True)),
                ('ruta_foto', models.ImageField(null=True, upload_to='usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('idTarjeta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.tarjeta')),
            ],
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.usuario'),
        ),
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarioPrincipal', to='administrador.usuario')),
                ('idUsuarioSeguidor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarioSeguidor', to='administrador.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('idLicencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('estado', models.BooleanField()),
                ('idPaquete', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.paquete')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idFoto', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.ImageField(null=True, upload_to='anuncios')),
                ('idAnuncio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_guardado', models.DateField()),
                ('idAnuncio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.anuncio')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='idLicencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.licencia'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='idServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.servicio'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.usuario'),
        ),
    ]
