# Generated by Django 3.2.7 on 2021-11-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['-nombre']},
        ),
    ]
