# Generated by Django 3.2.7 on 2021-10-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cuenta',
            field=models.EmailField(max_length=80, unique=True),
        ),
    ]
