# Generated by Django 3.2.7 on 2021-11-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_servicio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='licencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='anunciosLicencia', to='administrador.licencia'),
        ),
    ]
