# Generated by Django 3.2.7 on 2021-11-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_anuncio_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='estado',
            field=models.CharField(blank=True, default='A', max_length=1, null=True),
        ),
    ]
