# Generated by Django 3.2.7 on 2021-10-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_usuario_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='idAnuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.anuncio'),
        ),
    ]
