# Generated by Django 3.2.7 on 2021-11-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_anuncio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rutaimagen',
            field=models.ImageField(blank=True, default='static/fotonn.png', null=True, upload_to='usuarios'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='rutaimagen',
            field=models.ImageField(default='static/fotonn.png', upload_to='anuncios'),
        ),
    ]
