# Generated by Django 3.2.7 on 2021-11-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_alter_perfil_rutaimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rutaimagen',
            field=models.ImageField(default='usuarios/fotonn.png', upload_to='usuarios'),
        ),
    ]
