# Generated by Django 3.2.7 on 2021-11-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_alter_perfil_rutaimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='telefono',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
