# Generated by Django 3.2.7 on 2021-11-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_anuncio_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='referencia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
