# Generated by Django 3.2.7 on 2021-11-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_alter_anuncio_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='numeroTarjeta',
            field=models.CharField(max_length=16),
        ),
    ]
