# Generated by Django 3.2.7 on 2021-11-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_alter_tarjeta_numerotarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='rutaimagen',
            field=models.ImageField(blank=True, null=True, upload_to='anuncios'),
        ),
    ]
