# Generated by Django 3.2.7 on 2021-12-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0012_auto_20211201_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rutaimagen',
            field=models.ImageField(blank=True, default='usuarios/fotonn.png', null=True, upload_to='usuarios'),
        ),
    ]
