# Generated by Django 3.2.7 on 2021-12-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_alter_perfil_rutaimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='confirmada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
