# Generated by Django 3.2.7 on 2021-12-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0014_alter_perfil_confirmada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='tarjeta',
        ),
        migrations.AddField(
            model_name='venta',
            name='numeroTarjeta',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
