# Generated by Django 3.2.7 on 2021-12-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0015_auto_20211202_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
