# Generated by Django 3.2.7 on 2021-12-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0016_delete_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
