# Generated by Django 3.2.7 on 2021-12-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0017_alter_licencia_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
