# Generated by Django 3.2.7 on 2021-12-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0018_alter_licencia_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
