# Generated by Django 3.2.7 on 2021-12-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0019_alter_paquete_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
