# Generated by Django 3.2.7 on 2021-12-04 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0020_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
