# Generated by Django 3.2.7 on 2021-12-04 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0021_auto_20211204_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventasUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
